import{j as d}from"./jsx-runtime-Cf8x2fCZ.js";import{c as g}from"./KcPageStory-CuybM4jV.js";import"./index-yBjzXJbu.js";import"./KcPage-Bf8_W5ld.js";import"./iframe-DOGX7Igh.js";import"./index-BlmOqGMO.js";import"./kc.gen-DublLCkN.js";import"./assert-lEPzpKR_.js";import"./button-C_ykKUfv.js";import"./index-Dv8KEsPl.js";import"./index-Dp3B9jqt.js";import"./clsx-B-dksMZM.js";import"./utils-CKXzwFwe.js";import"./createLucideIcon-C49h6iyD.js";import"./index-RG4fqDpO.js";import"./index-fNjTmf9T.js";import"./index-BdQq_4o_.js";import"./index-Cnu3ZVWt.js";import"./dropdown-menu-6x-QXDHJ.js";import"./index-De3Pmiai.js";import"./index-C6-d9oZJ.js";import"./index-xprPBo3d.js";import"./index-DZ2oWOeb.js";import"./mode-toggle-nGGCW_pk.js";import"./card-sF6WieIs.js";/* empty css              */const{KcPageStory:o}=g({pageId:"login-recovery-authn-code-config.ftl"}),z={title:"login/login-recovery-authn-code-config.ftl",component:o},e={render:()=>d.jsx(o,{})},r={render:()=>d.jsx(o,{kcContext:{url:{loginAction:"/mock-login-action"},message:{summary:"An error occurred during recovery code generation. Please try again.",type:"error"}}})};var t,n,i;e.parameters={...e.parameters,docs:{...(t=e.parameters)==null?void 0:t.docs,source:{originalSource:`{
  render: () => <KcPageStory />
}`,...(i=(n=e.parameters)==null?void 0:n.docs)==null?void 0:i.source}}};var a,s,c,m,p;r.parameters={...r.parameters,docs:{...(a=r.parameters)==null?void 0:a.docs,source:{originalSource:`{
  render: () => <KcPageStory kcContext={{
    url: {
      loginAction: "/mock-login-action"
    },
    message: {
      summary: "An error occurred during recovery code generation. Please try again.",
      type: "error"
    }
  }} />
}`,...(c=(s=r.parameters)==null?void 0:s.docs)==null?void 0:c.source},description:{story:`WithErrorDuringCodeGeneration:
- Purpose: Tests when an error occurs while generating recovery authentication codes.
- Scenario: The component renders an error message to inform the user of the failure during code generation.
- Key Aspect: Ensures that error messages are properly displayed when recovery code generation fails.`,...(p=(m=r.parameters)==null?void 0:m.docs)==null?void 0:p.description}}};const B=["Default","WithErrorDuringCodeGeneration"];export{e as Default,r as WithErrorDuringCodeGeneration,B as __namedExportsOrder,z as default};
